# Generated by Django 5.2.7 on 2025-11-18 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alter_usuario_correo_alter_usuario_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='forzar_cambio_contrasena',
            field=models.BooleanField(default=True, verbose_name='Forzar cambio de contraseña'),
        ),
    ]
