# Generated by Django 5.2.7 on 2025-11-25 19:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='stock_maximo',
            field=models.IntegerField(default=100, verbose_name='Stock Máximo'),
        ),
        migrations.AddField(
            model_name='inventario',
            name='stock_minimo',
            field=models.IntegerField(default=10, verbose_name='Stock Mínimo'),
        ),
        migrations.CreateModel(
            name='AlertaInventario',
            fields=[
                ('id_alerta', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_alerta', models.CharField(choices=[('stock_bajo', 'Stock Bajo'), ('stock_critico', 'Stock Crítico'), ('stock_alto', 'Stock Alto')], max_length=20, verbose_name='Tipo de Alerta')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Resolución')),
                ('resuelta', models.BooleanField(default=False, verbose_name='Resuelta')),
                ('notificado', models.BooleanField(default=False, verbose_name='Notificado')),
                ('inventario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='inventarios.inventario', verbose_name='Inventario')),
            ],
            options={
                'verbose_name': 'Alerta de Inventario',
                'verbose_name_plural': 'Alertas de Inventario',
                'db_table': 'alerta_inventario',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id_movimiento', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_movimiento', models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida'), ('ajuste', 'Ajuste'), ('transferencia', 'Transferencia')], max_length=20, verbose_name='Tipo de Movimiento')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad')),
                ('cantidad_anterior', models.IntegerField(verbose_name='Cantidad Anterior')),
                ('cantidad_nueva', models.IntegerField(verbose_name='Cantidad Nueva')),
                ('fecha_movimiento', models.DateTimeField(auto_now_add=True, verbose_name='Fecha del Movimiento')),
                ('proveedor', models.CharField(blank=True, max_length=200, null=True, verbose_name='Proveedor')),
                ('motivo', models.TextField(blank=True, null=True, verbose_name='Motivo/Observaciones')),
                ('inventario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='inventarios.inventario', verbose_name='Inventario')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Movimiento de Inventario',
                'verbose_name_plural': 'Movimientos de Inventario',
                'db_table': 'movimiento_inventario',
                'ordering': ['-fecha_movimiento'],
            },
        ),
    ]
