# Generated by Django 5.2.7 on 2025-12-05 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Categoría'),
        ),
        migrations.AddField(
            model_name='producto',
            name='control_por_lote',
            field=models.BooleanField(default=False, verbose_name='Control por Lote'),
        ),
        migrations.AddField(
            model_name='producto',
            name='control_por_serie',
            field=models.BooleanField(default=False, verbose_name='Control por Serie'),
        ),
        migrations.AddField(
            model_name='producto',
            name='costo_unitario',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Costo Unitario'),
        ),
        migrations.AddField(
            model_name='producto',
            name='ean_upc',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='EAN/UPC'),
        ),
        migrations.AddField(
            model_name='producto',
            name='factor_conversion',
            field=models.IntegerField(default=1, verbose_name='Factor de Conversión'),
        ),
        migrations.AddField(
            model_name='producto',
            name='ficha_tecnica_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL de Ficha Técnica'),
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL de Imagen'),
        ),
        migrations.AddField(
            model_name='producto',
            name='impuesto',
            field=models.IntegerField(default=19, verbose_name='Impuesto (%)'),
        ),
        migrations.AddField(
            model_name='producto',
            name='marca',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Marca'),
        ),
        migrations.AddField(
            model_name='producto',
            name='modelo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Modelo'),
        ),
        migrations.AddField(
            model_name='producto',
            name='perecedero',
            field=models.BooleanField(default=False, verbose_name='Perecedero'),
        ),
        migrations.AddField(
            model_name='producto',
            name='punto_reorden',
            field=models.IntegerField(blank=True, null=True, verbose_name='Punto de Reorden'),
        ),
        migrations.AddField(
            model_name='producto',
            name='sku',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='SKU'),
        ),
        migrations.AddField(
            model_name='producto',
            name='stock_maximo',
            field=models.IntegerField(blank=True, null=True, verbose_name='Stock Máximo'),
        ),
        migrations.AddField(
            model_name='producto',
            name='stock_minimo',
            field=models.IntegerField(default=0, verbose_name='Stock Mínimo'),
        ),
        migrations.AddField(
            model_name='producto',
            name='unidad_compra',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Unidad de Compra'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.CharField(blank=True, max_length=191, null=True, verbose_name='Descripción'),
        ),
    ]
