# Generated by Django 5.2.7 on 2025-11-25 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='rut',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='RUT/NIF'),
        ),
    ]
